In [1]:
import pandas as pd

In [2]:
path_folder = "Datasets/"
path_claims = "ClaimDetails_for_distribution.xlsx"
path_adjuster = "CatRosterReportDayOf_for_distribution_cleaned.xlsx"
path_dictionary = "Data_Set_decode_table_updated.xlsx"

In [3]:
ds_dictionary_claims = pd.read_excel(
    path_folder+path_dictionary,
    sheet_name=0
)

ds_dictionary_adjuster = pd.read_excel(
    path_folder+path_dictionary,
    sheet_name=1
)

ds_claims_main = pd.read_excel(
    path_folder+path_claims,
    sheet_name=0
)

ds_claims_explore = pd.read_excel(
    path_folder+path_claims,
    sheet_name=1
)

ds_adjuster_main = pd.read_excel(
    path_folder+path_adjuster,
    sheet_name=0
)

ds_adjuster_explore = pd.read_excel(
    path_folder+path_adjuster,
    sheet_name=1
)

In [16]:
ds_claims_main["Weather Text"].sort_values().unique()

array(['Flood                                                                           ',
       'Hail                                                                            ',
       'Hurricane or Tropical Storm - No Flooding                                       ',
       'Lightning (No Fire)                                                             ',
       'Non-submersion                                                                  ',
       'Other Flood                                                                     ',
       'Other Water Damage - weather                                                    ',
       'Other than Tornado, Hurricane, Tropical Storm - No Flooding                     ',
       'Other than Tornado, Hurricane, Tropical Storm with Flooding                     ',
       'Roof/Flashing Leak                                                              ',
       'Sewer/drain back-up                                                             ',
       'Submersion - On Water                                                           ',
       'Sump Overflow                                                                   ',
       'Tornado - No Flooding                                                           ',
       'Tornado with Flooding                                                           ',
       'Trailer Leak                                                                    ',
       'Water Seepage in Basement not from Sewer or Sump Back-Up                        ',
       'Window or Door                                                                  '],
      dtype=object)

In [6]:
ds_adjuster_main["Org Group"].sort_values().unique()

array([' ', 'Auto-Heavy Equipment', 'Auto-Product Development',
       "Business Insurance Claim-CAE's", 'Business Intelligence & Analyt',
       'Claim Shared Service-Business Process Services',
       'Claim Shared Service-CCS WKFC Mgmt & Analytics',
       'Claim University-Claim University', 'Connecticut',
       'Field & Financial Services-Claim Workforce Effectiveness',
       'Field & Financial Services-Mgmt  Finance & Strategy',
       'Field Operations-Metro New York - New Jersey',
       'Field Operations-Southern',
       'Field Operations-Southern California',
       'Finance & Fld Shd Svcs-ETM & Fraud Analytics',
       'Finance & Fld Shd Svcs-Shared & Vendor Services',
       'Finance-Claim-Finance', 'Florida',
       'General Liability-Complex Case',
       'General Liability-Field General Liability', 'Lake Michigan',
       'Metro New York - New Jersey', 'Mid-Atlantic', 'Mountain West',
       'New England', 'North Texas - Oklahoma',
       'Northern California - Nevada', 'Property-Cat',
       'Property-Property Field Trainers', 'Property-Property Large Loss',
       'Southern', 'Southern California',
       'Strategic Resolution Group-SRG Field',
       'Strategy Team-Communications', 'Subrogation-Subro - MCU', 'TIS',
       'Tennessee - Ohio Valley', 'Upper Midwest', 'Upstate New York',
       'Virginia - Carolina', 'Western Gulf',
       'Workers Comp-Product Development'], dtype=object)

In [7]:
ds_adjuster_main["Preferred Role"].sort_values().unique()

array(['Auto Appraiser', 'Auto Claim Unit Mgr', 'FNOL',
       'Property Claim Unit Mgr', 'Property Field Inspector',
       'Property Inside Claim Rep', 'Property Outside Claim Rep',
       'Property Outside Contents Claim Rep', 'Supervisor', nan],
      dtype=object)

In [10]:
ds_adjuster_main["Location"].sort_values().unique()

array(['Albany - Park Pl', 'Albuquerque-Lang Avenue',
       'Alpharetta-Atlanta', 'Austin-901 Mo-Pac', 'Bedford - Commerce',
       'Birmingham-Hoover', 'Blue Bell-Phil-Lakeview Dr',
       'Boise-Meridian', 'Boston-Financial Center',
       'Brookfield-Milwaukee', 'Buffalo', 'Centennial-Denver-Geddes',
       'Chantilly-WashingtnDC-PkMeadow', 'Charlotte-Carmel Commons',
       'Cincinnati-Elsinore', 'Columbus-Easton Oval',
       'Delaware - Virtual', 'Diamond Bar-Los Angeles',
       'Durham - Emperor Blvd', 'Edison-343 Thornall',
       'Exton-Philadelphia-Eagleview', 'Federal Way-Seattle-6th Ave',
       'Flowood-Jackson-Canebrake', 'Franklin-Nashville', 'Fresno',
       'Glendale-LosAngeles-655NCentrl', 'Glens Falls - Queensbury',
       'Hamden Law', 'Hartford - Tower', 'Hartford-Field', 'Honolulu',
       'Houston - Westway', 'Hudson - Boston',
       'Hunt Valley-Baltimore-Schilling', 'Independence-Cleveland',
       'Indianapolis - 96th St', 'Irvine-Los Angeles-Michelson',
       'Jacksonville Law', 'Knoxville', 'Las Vegas-Arroyo Crossing',
       'Little Rock', 'Louisville-Hurstbourne Pkwy', 'Marlton-Camden Law',
       'Maryland Heights-St. Louis', 'Massachusetts - Virtual',
       'Melville NY Corp Center Dr', 'Memphis-6750 Poplar',
       'Metairie-New Orleans-3900 Cswy', 'Morristown',
       'Naperville-Chicago', 'New York City - Lexington Ave',
       'North Dakota - Virtual', 'Oklahoma City Law', 'Omaha-Dodge Rd',
       'Orange-Los Angeles-Law', 'Orlando',
       'Overland Pk-Kansas City-132 St', 'Philadelphia-Market St',
       'Phoenix-Tatum Blvd', 'Pittsburgh-Washington Pl', 'Portland',
       'Providence Law', 'Raleigh', 'RanchoCordova-Sacramento-11090',
       'Richardson-Dallas', 'Richmond-Mayland Dr',
       'Rochester - Linden Oaks', 'Rosedale-Baltimore',
       'Salt Lake City-1100 E 6600', 'San Antonio-McAllister Fwy',
       'San Diego', 'South Carolina - Virtual', 'South Portland',
       'Spokane', 'St. Paul', 'Syracuse-Plainfield Rd',
       'Tampa - Dale Mabry', 'Troy-Detroit', 'Tulsa-5100 Skelly',
       'Vermont - Virtual', 'Walnut Creek-San Francisco-401',
       'Washington, DC - 13th Street', 'West Bridgewater',
       'West Des Moines-Jordan Creek', 'White Plains-Law1-Liability',
       'Windsor-Htfd-99 Lambrtn-ClaimU', 'Wyomissing-Reading'],
      dtype=object)

In [8]:
ds_adjuster_main["HR Job Title"].sort_values().unique()

array(['AVP, Claim Management', 'AVP, Complex Claim Liability',
       'AVP, Complex Claim Liability Specialist',
       'Account Underwriter, BSI Private Non-Profit', 'Acct Exec, BC',
       'Assoc Acct Exec, BSI Financial Institutions',
       'Assoc Acct Exec, BSI Private Non-Profit',
       'Assoc Acct Exec, Inland', 'Assoc Acct Exec, Oil & Gas',
       'Assoc Acct Exec, Select', 'Auto Salvage Coordinator', 'BI UPDP',
       'Benefit Management Case Manager',
       'Benefit Management Complex Case Manager', 'Benefit Mgmt Analyst',
       'Claim Account Executive', 'Claim Product Manager',
       'Claim Rep Trainee, Outside Property',
       'Claim Rep Trainee, Property Resolution',
       'Claim Rep Trainee, Subrogation',
       'Claim Rep Trainee, Workers Compensation',
       'Claim Rep, Auto Damage Specialist', 'Claim Rep, Auto FPM',
       'Claim Rep, Auto FPM Litigation/Arbitration', 'Claim Rep, Auto I',
       'Claim Rep, Auto II', 'Claim Rep, Auto Liability',
       'Claim Rep, Auto Liability F', 'Claim Rep, General Liability',
       'Claim Rep, Inside Property Hub', 'Claim Rep, Outside Property',
       'Claim Rep, Outside Property CAT',
       'Claim Rep, Outside Property Contents',
       'Claim Rep, Outside Property F', 'Claim Rep, Property Resolution',
       'Claim Rep, Property Resolution F', 'Claim Rep, Subrogation',
       'Claim Rep, Workers Compensation', 'Cnslt, Process Engineering',
       'Cons, Bus Insights Delivery', 'Cons, Business Process Mgmt',
       'Consultant, Claim Prod Mgt', 'Core Underwriter, Select',
       'Critical Claim Specialist', 'Critical Claim Specialist F',
       'Design Director', 'Dir, Accounting', 'Dir, Compliance',
       'Dir, Financial Analysis', 'Dir, QM', 'Director, Claim Management',
       'Director, Claim Management Outside Property',
       'Experienced Insurance Underwriting Professional',
       'Financial Analyst', 'Financial Consultant',
       'General Adjuster, BI', 'General Adjuster, PI',
       'Homeowner Liability & Loss Consultant',
       'Homeowner Liability & Loss Consultant F', 'Inside Auto Appraiser',
       'Investigative Case Manager', 'Learning Facilitator',
       'Major Case Spec, General Liability', 'Manager, QM',
       'Medical Case Manager', 'Medical Case Manager - Nurse Clinic',
       'Medical Team Leader', 'Mgr, Bus Perform Analytics',
       'Mgr, Compliance', 'NOLC, Auto',
       'New Business Underwriter, Select', 'OLDP Participant',
       'Outside Auto Appraiser', 'Project Director',
       'Property Field Training Manager',
       'QA Analyst, Auto Medical Appeals',
       'Return To Work Case Manager I', 'Return to Work Case Manager II',
       'Risk Control Assoc.', 'Risk Control Trainee',
       'SIU Desk Investigator', 'Scrum Master',
       'Specialist, Claim Operations', 'Sr Administrative Asst',
       'Sr Analyst, Claim Operations', 'Sr Claim Rep, Outside Property',
       'Sr Claim Rep, Outside Property CAT', 'Sr Compliance Consultant',
       'Sr Cons, Bus Insights Delivery', 'Sr Dir, Bus Perform Analytics',
       'Sr Dir, Financial Analysis', 'Sr Financial Consultant',
       'Sr Tech Spec, Auto Liability', 'Sr Tech Spec, Property',
       'Sr Tech Spec, Property F', 'Sr Tech Spec, Specialty Liability F',
       'Sr. QA Specialist', 'Tech Spec, Auto Liability',
       'Tech Spec, General Liability F',
       'Tech Spec, Heavy/Specialty Equipment', 'Tech Spec, Property',
       'Tech Spec, Property F', 'Tech Spec, SRG',
       'Tech Spec, Specialty Liability',
       'Tech Spec, Specialty Liability Outside',
       'Tech Spec, Subrogration', 'UPDP, Bond & SI',
       'Unit Manager, Auto Liability Major Case',
       'Unit Manager, Claim Customer Services', 'Unit Manager, Claim Ops',
       'Unit Manager, General Liability', 'Unit Manager, Inside Auto',
       'Unit Manager, Inside Property', 'Unit Manager, Outside Auto',
       'Unit Manager, Outside Property',
       'Unit Manager, Outside Property CAT', 'Unit Manager, Subrogation',
       'Unit Manager, Workers Compensation', 'Workforce Consultant',
       'Workforce Team Lead'], dtype=object)

In [9]:
ds_adjuster_main["HR Job Title"]

0      Claim Rep Trainee, Outside Property
1      Claim Rep Trainee, Outside Property
2      Claim Rep Trainee, Outside Property
3      Claim Rep Trainee, Outside Property
4      Claim Rep Trainee, Outside Property
                      ...
769         Tech Spec, Specialty Liability
770                       OLDP Participant
771          Sr Dir, Bus Perform Analytics
772                Unit Manager, Claim Ops
773                 Outside Auto Appraiser
Name: HR Job Title, Length: 774, dtype: object

In [ ]:
titles = (
    ds_adjuster_main["HR Job Title"]
    .dropna()
    .str.lower()
    .str.strip()
)

In [ ]:
JOB_TITLE_RULES = {
    "manager": [
        "manager",
        "mgr",
        "supervisor",
        "lead"
    ],
    "senior_adjuster": [
        "senior adjuster",
        "sr adjuster",
        "sr."
    ],
    "adjuster": [
        "adjuster",
        "claims rep",
        "claims representative"
    ],
    "analyst": [
        "analyst",
        "analysis"
    ],
    "director": [
        "director",
        "head of"
    ],
    "assistant": [
        "assistant",
        "asst"
    ]
}

In [13]:
ds_adjuster_main["Preferred Tour Length"].sort_values().unique()

array([14., 21., 28., nan])

In [16]:
ds_adjuster_main["Worksite Name"].unique()

array([nan, 'NCC Virtual FRT Support                           ',
       'Minneapolis, MN                                   ',
       'Cleveland, OH                                     ',
       'Natomas, CA                                       ',
       'Topeka, KS                                        ',
       'Lone Tree, CO                                     ',
       'Auto - Lawton, OK                                 ',
       'Greenville, SC                                    ',
       'Newton, IA                                        ',
       'White Plains, NY                                  ',
       'Auto - Little Rock, AR                            ',
       'Jamaica, NY                                       ',
       'New Stanton, PA                                   ',
       'Lexington, KY                                     ',
       'Sacramento, CA                                    ',
       'West Salem, WI                                    ',
       'Little Rock, AR - Local (CP)                      ',
       'Tucson, AZ - Local (CP)                           ',
       'Phoenix, AZ                                       ',
       'Columbia, IL - Local (CP)                         ',
       'Jeffersonville, IN                                ',
       'Cedar Park, TX - Local (CP)                       ',
       'Englewood, CO                                     ',
       'Aurora, MO - Local (CP)                           ',
       'Springdale, AR                                    ',
       'Beverly Hills, CA                                 ',
       'Las Vegas, NM                                     ',
       'Buffalo, NY                                       ',
       'Westminster, CO - Local (CP)                      ',
       'Houston, TX - Local (CP)                          ',
       'Bridgeport, CT - Local                            ',
       'Chantilly, VA                                     ',
       'Austin, TX                                        ',
       'San Antonio, TX                                   ',
       'Denver, CO                                        ',
       'Gaithersburg, MD                                  ',
       'Windsor, CT                                       ',
       'Virtual M-F Auto Support                          ',
       'Edison, NJ - Local (CP)                           ',
       'Elk Grove, CA                                     ',
       'Columbia, MO                                      ',
       'Lakewood, CO                                      ',
       'Ames, IA                                          ',
       'Moscow Mills, MO - Local (CP)                     ',
       'Auto - Edison, NJ                                 ',
       'Waterloo, IA                                      ',
       'Nashville, TN                                     ',
       'Auto - Fresh Meadows, NY                          ',
       'Longmont, CO                                      ',
       'Denver, CO - Local (CP)                           ',
       'Colorado Springs, CO - Local (CP)                 ',
       'Track 1321 - Virtual Deployment M-F               ',
       'Des Moines, IA                                    ',
       'Little Rock, AR                                   ',
       'ICR- Claim University                             ',
       'Atlanta, GA                                       ',
       'Inside Claim Rep- Phase 2                         ',
       'BI Virtual Support                                ',
       'Auto - Scottsdale, AZ                             ',
       'FRT Inside Support - Virginia-Carolina Virtual M-F',
       'Legacy ERT Volunteers                             ',
       'VADC Virtual Inside ERT Support                   ',
       'Melville NY                                       ',
       'FRT Post BDE II Training                          ',
       'Independence, OH                                  ',
       'Dallas WC Supporting Property                     ',
       'FRT Inside Support - OCCRs - Virtual              ',
       'Edison, NJ                                        ',
       'Metro NY NJ IVI Dedication - Virtual              ',
       'Midwest City, OK                                  ',
       'FRT Inside Support - Lake Michigan Virtual M-F    ',
       'Copiague, NY - Local (CP)                         ',
       'CAT 68- Forrest Park                              ',
       'ERT Virtual Inside Support- Lake Michigan M-F     ',
       'Canton, MI                                        ',
       'Auto - Glastonbury, CT                            ',
       'Kansas City, KS                                   ',
       'Woburn, MA- TOM                                   ',
       'Kennesaw, GA                                      ',
       'Sterling, VA                                      ',
       'Virtual OCCR Wildfire Support - M-F - North CA    ',
       'Brookfield, CT - Local (CP)                       ',
       'Macon, GA                                         ',
       'Southington, CT                                   ',
       'Foxborough, MA                                    ',
       'Irving, TX                                        ',
       'Tupelo, MS                                        ',
       'Track 1220 - Virtual Deployment M-F               ',
       'Field Inspector- Phase 2                          ',
       'Medina, NY - Local (CP)                           ',
       'Rosemont, IL                                      ',
       'Auto - Moore, OK                                  ',
       'Arlington, VA                                     ',
       'North Texas Oklahoma - IVI Virtual Dedication     ',
       'Denver                                            ',
       'Clarksville, TN                                   ',
       'Auto - Bonita Springs, FL                         ',
       'Fairfax, VA                                       ',
       'ERT OCR - Somerset, NJ                            ',
       'ERT Inside Support - NPRC M-F - Virtual           ',
       'Newberry, SC - Local (CP)                         ',
       'Lake Michigan Virtual Estimator                   ',
       'Hastings, NE                                      ',
       'Auto Supporting Auto - Virtual M-F                ',
       'Scitico, CT - Local (CP)                          ',
       'Hartford, CT                                      ',
       'Elgin, SC - Local (CP)                            ',
       'FRT Inside Support - Mountain West Virtual M-F    ',
       'Plano, TX                                         ',
       'Auto - Round Rock, TX                             ',
       'Warrenton, VA - Local (CP)                        ',
       'Louisville, KY                                    ',
       'Bethlehem, PA - Local                             ',
       'Auto - Field Appraiser Support                    ',
       'Louisville, KY - Local (CP)                       ',
       'Lorain, OH - Local (CP)                           ',
       'Virtual Inside Appraisal Support                  ',
       'Cincinnati, OH                                    ',
       'Augusta, GA - Local (CP)                          ',
       'Track 320 - Virtual Deployment M-F                ',
       'Dallas, TX                                        ',
       "Auto - O'Fallon, MO                               ",
       'Track 1320 - Virtual Deployment M-F               ',
       'Track 120 - Virtual Deployment M-F                ',
       'Shawnee Missions, KS - Local (CP)                 ',
       'Field Inspector- Phase 1                          ',
       'Auto Express Virtual M-F Outside Auto Appraiser   ',
       'ERT Inside Support - NPRC - Virtual               ',
       'Track 1020 - Virtual Deployment M-F               ',
       'Remote Territory Virtual FRT Support M-F          ',
       'Houston, TX                                       ',
       'Auto - Yonkers, NY                                ',
       'Kenmore, NY - Local (CP)                          ',
       'Detroit, MI                                       ',
       'Douglasville, GA - Local (CP)                     ',
       'St. Paul, MN - ERT OCR - Local M-F                ',
       'Virtual IVI Support - Mountain West (AZ)          ',
       'Las Vegas, NV                                     ',
       'Cumming, GA                                       ',
       'Virtual Total Loss Support - Auto                 ',
       'Oklahoma City, OK                                 ',
       'Hartford, CT - Local (CP)                         ',
       'Dallas, TX - Local (CP)                           ',
       'Herndon, VA                                       ',
       'IL Review - Virtual M-F                           ',
       'Southaven, MS                                     ',
       'Omaha, NE                                         ',
       'St. Louis, MO - Local (CP)                        ',
       'Bowie, MD                                         ',
       'St. Louis, MO                                     ',
       'Yorkville, IL - Local (CP)                        ',
       'Huntsville, AL - Local (CP)                       ',
       'Track 1819 - Virtual Deployment M-F               ',
       'New City, NY - Local (CP)                         ',
       'Chattanooga, TN                                   ',
       'Track 920 - Virtual Deployment M-F                ',
       'Track 1420 - Virtual Deployment M-F               ',
       'Jackson, MS - Local (CP)                          ',
       'Forsyth, IL - Local (CP) Staffing                 ',
       'Track 121 - Virtual Deployment M-F                ',
       'Columbus, OH - Local (CP)                         ',
       'Athens, GA - Local (CP)                           ',
       'Woodruff, SC - Local (CP)                         ',
       'Roseville, CA                                     ',
       'Great Bend, KS                                    ',
       'NCC Virtual Resolution M-F                        ',
       'Garden City, NY                                   ',
       'Fort Collins, CO - Local (CP)                     ',
       'Auto - Virtual TL & Salvage Support               ',
       'Brookfield, CT                                    ',
       'Aurora, CO - Local (CP)                           ',
       'Albuquerque, NM                                   ',
       'Tucson, AZ                                        ',
       'Spokane, WA                                       ',
       'NCC Virtual Resolution                            ',
       'Fort Worth, TX                                    ',
       'Springfield, MA - Local (CP)                      ',
       'Plymouth, MA - Local (CP)                         ',
       'Eugene, OR - MCU Support                          ',
       'Zanesville, OH                                    ',
       'RT IVI Dedication - M-F                           ',
       'Hixson, TN - Local (CP)                           ',
       'Rio Rancho, NM - Local (CP)                       ',
       'ICR- NCC                                          ',
       'Springfield, MA                                   ',
       'Granbury, TX - Local (CP)                         ',
       'Virtual Total Loss Support                        ',
       'Linthicum, MD                                     ',
       'Virtual CAT Support                               ',
       'Berwyn, PA                                        ',
       'Chicago, IL - Local (CP)                          ',
       'Rockford, IL - Local M-F                          ',
       'Woodridge, IL - Local (CP)                        ',
       'Dallas TX                                         ',
       'Virtual FRT Support                               ',
       'Track 721 - Virtual Deployment M-F                ',
       'ERT Scoper - Joliet, IL                           ',
       'White Plans, NY                                   ',
       'El Paso, TX                                       ',
       'OCCR Virtual Support                              ',
       'Virtual M-F Heavy Equipment ER Support            ',
       'Local ERT Melville                                ',
       'Track 621 - Virtual Deployment M-F                ',
       'ERT OCR - Nashville, TN - Local                   ',
       'Kennesaw, GA - Local (CP)                         ',
       'Omaha, NE - Local (CP)                            ',
       'Keep and Close Support                            ',
       'Northfield, VT - Local (CP)                       ',
       'Finneytown, OH - Local (CP)                       ',
       'Lincoln, NE                                       ',
       'N CA WC Supporting Property                       ',
       'ERT Virtual Inside Support - Western Gulf M-F     ',
       'Hunt Valley, MD                                   ',
       'Orange, CT - Local (CP)                           ',
       'Ringwood, NJ - Local (CP)                         ',
       'Charlotte Liability Supporting Property           ',
       'ERT Scoper - Garden City, NY                      ',
       'Auto - Hot Springs, AR                            ',
       'North Chesterfield, VA - Local (CP)               ',
       'Appraisal Hub - Virtual Inspection Support        ',
       'Smithtown, NY - Local (CP)                        ',
       'North Little Rock, AR                             ',
       'Western Gulf - IVI Virtual Dedication             ',
       'ERT Inside Support - Western Gulf M-F             ',
       'N. CA Auto Supporting Property                    ',
       'Huntsville, TX - Local                            ',
       'Grafton, OH - Local (CP)                          ',
       'National Claim Center                             ',
       'Burbank, CA                                       ',
       'ERT Virtual Inside Support - Mountain West        ',
       'Auto - Brentwood, TN                              ',
       'Savannah, GA - Local                              ',
       'Beech Grove, IN                                   ',
       'Auto - Lubbock, TX                                ',
       'Auto - Colorado Springs, CO                       ',
       'Lexington, KY - Local (CP)                        ',
       'Auto Express and Blend Support - Virtual M-F      ',
       'Bristol, CT - Local (CP)                          ',
       'Track 1221 - Virtual Deployment M-F               ',
       'Track 1120 - Virtual Deployment M-F               ',
       'Jonesboro, GA - Local (CP)                        ',
       'Local M-F Auto Support                            ',
       'Marietta, GA - Local (CP)                         ',
       'Pearl, MS                                         ',
       'Middlebury, CT - Local (CP)                       ',
       'Eden Prairie, MN                                  ',
       'Track 1021 - Virtual Deployment M-F               ',
       'Waltham, MA                                       ',
       'Jackson, MS                                       ',
       'Davenport, IA                                     ',
       'San Diego, CA                                     ',
       'Virtual IVI Support                               ',
       'Indianapolis, IN                                  ',
       'Salem, AL - Local (CP)                            ',
       'Auto - Annapolis, MD                              ',
       'Track 1521 - Virtual Deployment M-F               ',
       'Western Gulf Virtual FRT Res Support M-F          ',
       'Silver Spring, MD                                 ',
       'Concord, NH - Local (CP)                          ',
       'Track 1421 - Virtual Deployment M-F               ',
       'Denver Liability Supporting Property              ',
       'Track 620 - Virtual Deployment M-F                ',
       'Local Auto Support                                ',
       'Seattle, WA                                       ',
       'Auto - Golden, CO                                 ',
       'Midlothian, VA                                    ',
       'Montgomery, AL - Local (CP)                       ',
       'Virtual FRT Estimator - Upper Midwest             ',
       'Virtual Claim Experience- WA                      ',
       'Auto - Fort Worth, TX                             ',
       'Virtual OCCR Support                              ',
       'ERT Estimators - Rosemont, IL                     ',
       'Ohio Property File Review                         ',
       'NCA Virt Support - FRT                            ',
       'Tuscaloosa, AL                                    ',
       'Mission Valley, CA                                ',
       'Auto - Virtual TL & Salvage Support M-F           ',
       'Virtual ERT Estimator - Metro NY - NJ             ',
       'Auto - MN M-F Outside Appraisal Support           ',
       'Virtual UM Support - M-F                          ',
       'Auto - Bedford, TX                                ',
       'Manhattan, NY - ERT                               ',
       'ERT Virtual Inside Support - Florida M-F          ',
       'Pittsburgh, PA - Local (CP)                       ',
       'Inside Claim Rep- Phase 1                         ',
       'ERT ICR FNOL Support - Virtual                    ',
       'ERT OCR - Bethlehem, PA                           ',
       'VA DC Ops Supporting Property                     ',
       'ERT Virtual Inside Support - NCC                  ',
       'New Jersey Local ERT                              ',
       'MS Review - Virtual M-F                           ',
       'ERT Virtual Inside Support - Virginia-Carolina    ',
       'Portland, OR                                      ',
       'Queens, NY                                        ',
       'Capstone Deployment                               ',
       'Golden, CO                                        ',
       'NCC Total Loss Support - Upstate NY               ',
       'Salvage Task Support                              ',
       'Richmond, VA - Local - M-F                        ',
       'Virtual Inside Support                            '], dtype=object)

In [75]:
ds_claims_main["Policy Form Desc"].unique()

array(['SPECIAL HOMEOWNERS FORM - DWELLING (HOMEPAC)                                                        ',
       'Commercial Property Deluxe Program - Simp. OCC. BI / Comm Mult Peril                                ',
       'MPAC CLAIMS MADE - OCCURRENCE                                                                       ',
       'High Value Home                                                                                     ',
       'TENANTS FORM (HOMEPAC)                                                                              ',
       'Landlord Dwelling Form                                                                              ',
       'CONDOMINIUM HOME OWNERS FORM (HOMEPAC)                                                              ',
       'RENTAL DWELLING FORM (HOMESAVER)                                                                    ',
       'Farm - BI Package Simp. o/t f/r Comb. Coverage Plan BI / Comm Mult Peril                            ',
       nan,
       'BROAD HOME OWNERS FORM - DWELLING (HOMEPAC)                                                         ',
       'RENTAL CONDOMINIUM UNIT FORM (HOMESAVER)                                                            ',
       'CO-OP NEW YORK ONLY                                                                                 ',
       'NORTH CAROLINA HIGH VALUE DWELLING ISO 2000                                                         ',
       'COMPREHENSIVE BUSINESS POLICY  (MANUSCRIPT NAG ONLY)                                                ',
       'Landlord Condominium Form                                                                           ',
       'COMMERCIAL PACKAGE PROGRAM - SIMP. OCCUR. O/T FR COMB                                               ',
       'Tap Boat Policy PI / All Lines                                                                      ',
       'Wedding                                                                                             ',
       'SIMPLIFIED FARM/RANCH COMBINATION COV. PLAN                                                         ',
       'HOMEOWNERS - OBSOLETE AND REUSED FOR DWELLING FIRE                                                  '],
      dtype=object)

In [21]:
ds_claims_main["Peril Group"].unique()

array(['Wind', 'Hail', 'Water (W)', 'All Other Weather'], dtype=object)

In [22]:
ds_claims_main["Weather Text"].unique()

array(['Tornado - No Flooding                                                           ',
       'Hail                                                                            ',
       'Other than Tornado, Hurricane, Tropical Storm - No Flooding                     ',
       'Flood                                                                           ',
       'Roof/Flashing Leak                                                              ',
       'Lightning (No Fire)                                                             ',
       'Other Water Damage - weather                                                    ',
       'Water Seepage in Basement not from Sewer or Sump Back-Up                        ',
       'Other than Tornado, Hurricane, Tropical Storm with Flooding                     ',
       'Hurricane or Tropical Storm - No Flooding                                       ',
       'Sump Overflow                                                                   ',
       'Sewer/drain back-up                                                             ',
       'Window or Door                                                                  ',
       'Other Flood                                                                     ',
       'Trailer Leak                                                                    ',
       'Tornado with Flooding                                                           ',
       'Non-submersion                                                                  ',
       'Submersion - On Water                                                           '],
      dtype=object)

In [24]:
ds_adjuster_main["Deployed Role"].unique()

array([nan, 'Property Outside Claim Rep', 'Property Inside Claim Rep',
       'Auto Appraiser', 'Property Claim Unit Mgr',
       'Property Field Inspector', 'Property Outside Contents Claim Rep',
       'Auto Claim Unit Mgr',
       'Auto Inside Claim Rep - Personal Insurance', 'Auto CAT Mgr',
       'Other', 'Auto Heavy Equipment Appraiser', 'FNOL'], dtype=object)

In [25]:
ds_adjuster_main["WFM Resource Type Desc"].unique()

array(['FRT (Property)', 'ERT (Field)', 'CAT', 'ERT (Non Field)'],
      dtype=object)

In [79]:
ds_claim_main["Weather"].unique()

NameError: name 'ds_claim_main' is not defined

In [34]:
ds_adjuster_main[["Tour Start Date", "Tour End Date"]]

         Tour Start Date        Tour End Date
0                    NaN                  NaN
1                    NaN                  NaN
2                    NaN                  NaN
3                    NaN                  NaN
4                    NaN                  NaN
..                   ...                  ...
769  2017-08-31 00:00:00  2017-09-15 00:00:00
770  2012-04-01 00:00:00  2012-04-01 00:00:00
771  2012-04-01 00:00:00  2012-04-02 00:00:00
772  2012-04-01 00:00:00  2012-04-02 00:00:00
773                  NaN                  NaN

[774 rows x 2 columns]

In [54]:
ds_claims_main["Claim Number"].count(

np.int64(1065)

In [40]:
ds_adjuster_main["Current Status End"].sort_values(ascending=False).unique()

<DatetimeArray>
['2099-01-01 00:00:00', '2050-03-03 00:00:00', '2028-12-31 00:00:00',
 '2025-12-31 00:00:00', '2025-06-16 00:00:00', '2025-02-28 00:00:00',
 '2025-01-31 00:00:00', '2025-01-20 00:00:00', '2025-01-16 00:00:00',
 '2024-12-31 00:00:00',
 ...
 '2022-08-14 00:00:00', '2022-08-13 00:00:00', '2022-08-12 00:00:00',
 '2022-08-11 00:00:00', '2022-08-10 00:00:00', '2022-08-09 00:00:00',
 '2022-08-08 00:00:00', '2022-08-07 00:00:00', '2022-08-06 00:00:00',
 '2022-08-05 00:00:00']
Length: 193, dtype: datetime64[ns]

In [21]:
ds_claims_main["Peril Description"].unique()

array(['Wind', 'Hail', 'Water Damage - Weather', 'Lightning',
       'Water Damage - Sewer or Sump Backup', 'Flood', 'Windstorm'],
      dtype=object)

In [73]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)


table = pd.crosstab(
    ds_adjuster_main["HR Job Title"],
    ds_adjuster_main["CL Skill Level"]
)

table

CL Skill Level                                     0   1   2   3   4   5
HR Job Title
AVP, Claim Management                              1   0   0   0   0   0
AVP, Complex Claim Liability                       0   0   0   1   0   0
AVP, Complex Claim Liability Specialist            0   0   1   0   0   0
Account Underwriter, BSI Private Non-Profit        0   1   0   0   0   0
Acct Exec, BC                                      1   0   0   0   0   0
Assoc Acct Exec, BSI Financial Institutions        0   1   0   0   0   0
Assoc Acct Exec, BSI Private Non-Profit            1   0   0   0   0   0
Assoc Acct Exec, Inland                            0   0   1   0   0   0
Assoc Acct Exec, Oil & Gas                         0   0   1   0   0   0
Assoc Acct Exec, Select                            2   0   0   0   0   0
Auto Salvage Coordinator                           1   0   0   1   0   0
BI UPDP                                            1   6   0   0   0   0
Benefit Management Case Manager                    1   1   0   0   0   0
Benefit Management Complex Case Manager            1   0   0   0   0   0
Benefit Mgmt Analyst                               0   0   1   0   0   0
Claim Account Executive                            0   1   0   1   0   0
Claim Product Manager                              6   0   0   0   0   0
Claim Rep Trainee, Outside Property               15   1   0   0   0   0
Claim Rep Trainee, Property Resolution             2   1   0   0   0   0
Claim Rep Trainee, Subrogation                     0   1   0   0   0   0
Claim Rep Trainee, Workers Compensation            2   0   0   0   0   0
Claim Rep, Auto Damage Specialist                  1   0   0   0   0   0
Claim Rep, Auto FPM                                6   1   0   0   0   0
Claim Rep, Auto FPM Litigation/Arbitration         3   0   0   0   0   0
Claim Rep, Auto I                                  4   2   0   0   1   0
Claim Rep, Auto II                                 1   3   0   0   0   0
Claim Rep, Auto Liability                          5   1   0   1   0   0
Claim Rep, Auto Liability F                        3   0   0   0   0   0
Claim Rep, General Liability                       3   1   0   0   0   0
Claim Rep, Inside Property Hub                     0   0   0   1   0   0
Claim Rep, Outside Property                      124  70  14  24   4   0
Claim Rep, Outside Property CAT                    1   6   0   0   0   0
Claim Rep, Outside Property Contents               1   1   0   8   1   0
Claim Rep, Outside Property F                      9   9   0   4   0   0
Claim Rep, Property Resolution                    16   4   4   2   1   0
Claim Rep, Property Resolution F                   0   0   0   1   0   0
Claim Rep, Subrogation                             0   2   0   0   0   0
Claim Rep, Workers Compensation                    2   1   0   0   0   0
Cnslt, Process Engineering                         1   0   0   0   0   0
Cons, Bus Insights Delivery                        1   0   0   0   0   0
Cons, Business Process Mgmt                        0   0   1   0   0   0
Consultant, Claim Prod Mgt                         1   0   0   0   0   0
Core Underwriter, Select                           0   0   0   1   0   0
Critical Claim Specialist                          1   4   0   0   0   0
Critical Claim Specialist F                        2   2   1   0   0   0
Design Director                                    1   0   0   0   0   0
Dir, Accounting                                    1   0   0   0   0   0
Dir, Compliance                                    1   0   0   0   0   0
Dir, Financial Analysis                            1   0   0   0   0   0
Dir, QM                                            0   0   0   0   0   1
Director, Claim Management                         1   0   0   1   0   0
Director, Claim Management Outside Property        0   0   0   1   1   0
Experienced Insurance Underwriting Professional    1   1   0   0   0   0
Financial Analyst                                  0   0   0   0   0   1
Financial Consultant                               0   0   1   0   0   0
General Adjuster, BI                               0   0   0   0   0   2
General Adjuster, PI                               0   0   0   2   1   0
Homeowner Liability & Loss Consultant              1   1   0   0   0   0
Homeowner Liability & Loss Consultant F            0   0   0   1   0   0
Inside Auto Appraiser                              4   4   1   0   0   0
Investigative Case Manager                         7   3   0   0   0   0
Learning Facilitator                               1   0   0   0   0   0
Major Case Spec, General Liability                 1   0   0   0   0   0
Manager, QM                                        0   1   0   0   0   0
Medical Case Manager                               2   5   0   0   0   0
Medical Case Manager - Nurse Clinic                2   0   0   0   0   0
Medical Team Leader                                1   0   0   0   0   0
Mgr, Bus Perform Analytics                         0   0   1   0   0   0
Mgr, Compliance                                    1   0   0   0   0   0
NOLC, Auto                                         0   0   1   0   0   0
New Business Underwriter, Select                   2   0   0   1   0   0
OLDP Participant                                   0   0   0   1   0   0
Outside Auto Appraiser                            37  13   8   6   0   0
Project Director                                   0   0   0   0   0   1
Property Field Training Manager                    0   0   1   1   1   1
QA Analyst, Auto Medical Appeals                   0   1   0   0   0   0
Return To Work Case Manager I                      5   4   0   0   0   0
Return to Work Case Manager II                     1   5   0   0   0   0
Risk Control Assoc.                                0   1   0   0   0   0
Risk Control Trainee                               1   0   0   0   0   0
SIU Desk Investigator                              1   0   0   0   0   0
Scrum Master                                       1   0   0   0   0   0
Specialist, Claim Operations                       4   0   1   0   0   0
Sr Administrative Asst                             1   0   0   0   0   0
Sr Analyst, Claim Operations                       0   0   1   0   0   0
Sr Claim Rep, Outside Property                     3  14  12  10   6   1
Sr Claim Rep, Outside Property CAT                 0   0   0   2   0   0
Sr Compliance Consultant                           0   1   0   0   0   0
Sr Cons, Bus Insights Delivery                     2   0   0   0   0   0
Sr Dir, Bus Perform Analytics                      1   0   0   0   0   0
Sr Dir, Financial Analysis                         1   0   0   0   0   0
Sr Financial Consultant                            2   0   0   0   0   0
Sr Tech Spec, Auto Liability                       2   1   0   0   0   0
Sr Tech Spec, Property                             0   0   0   0   0   2
Sr Tech Spec, Property F                           0   0   0   0   1   0
Sr Tech Spec, Specialty Liability F                1   0   0   0   0   0
Sr. QA Specialist                                  0   0   0   1   0   0
Tech Spec, Auto Liability                          4   1   0   1   0   0
Tech Spec, General Liability F                     2   0   1   0   0   0
Tech Spec, Heavy/Specialty Equipment               0   0   0   1   0   0
Tech Spec, Property                                2   3   9  10   8  10
Tech Spec, Property F                              0   0   1   2   1   0
Tech Spec, SRG                                     1   0   0   0   0   0
Tech Spec, Specialty Liability                     0   1   0   0   0   0
Tech Spec, Specialty Liability Outside             1   0   0   0   0   0
Tech Spec, Subrogration                            1   1   0   0   0   0
UPDP, Bond & SI                                    1   0   0   0   0   0
Unit Manager, Auto Liability Major Case            0   1   0   0   0   0
Unit Manager, Claim Customer Services              1   0   0   0   0   0
Unit Manager, Claim Ops                            1   1   0   0   0   0
Unit Manager, General Liability                    1   1   0   0   0   0
Unit Manager, Inside Auto                          8   4   0   2   0   0
Unit Manager, Inside Property                      0   0   0   1   1   0
Unit Manager, Outside Auto                         1   0   0   0   0   0
Unit Manager, Outside Property                     2   1   7  13  10   9
Unit Manager, Outside Property CAT                 0   0   0   0   0   1
Unit Manager, Subrogation                          0   0   1   0   0   0
Unit Manager, Workers Compensation                 5   2   0   2   0   0
Workforce Consultant                               1   0   0   0   0   0
Workforce Team Lead                                1   0   0   0   0   0

In [27]:
table = pd.crosstab(
    ds_adjuster_main["WFM Resource Type Desc"],
    ds_adjuster_main["PL Skill Level"]
)

table

PL Skill Level            0   1    2    3   4   5
WFM Resource Type Desc
CAT                       0   0    1    7   1   1
ERT (Field)             108  62   25   29   5   1
ERT (Non Field)          36   7    4   21   6   4
FRT (Property)           14  13  109  234  59  27

In [76]:
ds_claims_main.columns

Index(['Weather', 'Territory', 'Claim Number', 'CAT Code', 'CAT Severity Code',
       'Loss Date', 'NOL Date', 'Peril Description', 'Cause Of Injury Text',
       'Peril Group', 'Weather Indicator', 'Weather Text', 'Division',
       'Accident City', 'Accident State', 'Accident Zip', 'Claimant Number',
       'Loss Type', 'Policy Form Desc', '6_cluster_cluster_id',
       '6_cluster_distance_to_centroid_km', '7_cluster_cluster_id',
       '7_cluster_distance_to_centroid_km', '8_cluster_cluster_id',
       '8_cluster_distance_to_centroid_km', '9_cluster_cluster_id',
       '9_cluster_distance_to_centroid_km', '10_cluster_cluster_id',
       '10_cluster_distance_to_centroid_km'],
      dtype='object')

In [78]:
ds_claims_main["Weather Text"].unique()

array(['Tornado - No Flooding                                                           ',
       'Hail                                                                            ',
       'Other than Tornado, Hurricane, Tropical Storm - No Flooding                     ',
       'Flood                                                                           ',
       'Roof/Flashing Leak                                                              ',
       'Lightning (No Fire)                                                             ',
       'Other Water Damage - weather                                                    ',
       'Water Seepage in Basement not from Sewer or Sump Back-Up                        ',
       'Other than Tornado, Hurricane, Tropical Storm with Flooding                     ',
       'Hurricane or Tropical Storm - No Flooding                                       ',
       'Sump Overflow                                                                   ',
       'Sewer/drain back-up                                                             ',
       'Window or Door                                                                  ',
       'Other Flood                                                                     ',
       'Trailer Leak                                                                    ',
       'Tornado with Flooding                                                           ',
       'Non-submersion                                                                  ',
       'Submersion - On Water                                                           '],
      dtype=object)